# Generated by Django 4.1.4 on 2023-08-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='solution_id_lists',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.JSONField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='question_id_lists',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
