# Generated by Django 4.1.4 on 2023-06-14 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_ability_solution_difficulty'),
        ('common', '0002_usersubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='question.ability'),
        ),
    ]
