# Generated by Django 4.1.4 on 2023-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_task_solution_id_lists_task_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='solved_prblem',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_programming',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
