# Generated by Django 4.1.4 on 2024-03-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_userability'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(auto_now_add=True)),
                ('ability_score', models.IntegerField()),
                ('user_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.userability')),
            ],
        ),
    ]
