# Generated by Django 4.1.4 on 2024-03-16 01:24

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_abilityhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ability',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='user',
            name='solved_problem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year_of_programming',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_type', models.IntegerField(choices=[(0, 'Submission')], default=0)),
                ('content', models.JSONField(default=common.models.get_default_json)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
