# Generated by Django 4.1.4 on 2023-06-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_user_ability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ability',
            new_name='abilityId',
        ),
        migrations.RenameField(
            model_name='usersubmission',
            old_name='content',
            new_name='categoryIds',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='details',
            field=models.JSONField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='keypoint',
            field=models.JSONField(blank=True, default=1, help_text='list of completed keypoint id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='questionId',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='solutionId',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='userId',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
