# Generated by Django 4.1.4 on 2023-07-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_ability_user_abilityid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ability_id',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='details',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='keypoint',
        ),
        migrations.AddField(
            model_name='user',
            name='ability',
            field=models.JSONField(default={'data': [0]}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='code',
            field=models.JSONField(blank=True, default={'data': ''}, help_text='code in submission'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='completeness',
            field=models.JSONField(default={'data': ''}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='category_id_list',
            field=models.JSONField(help_text='list of validated category ids'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='question_id',
            field=models.BigIntegerField(help_text='question id (Question.id)'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='solution_id',
            field=models.BigIntegerField(help_text='solution_id (Solution.id)'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='user_id',
            field=models.BigIntegerField(help_text='user_id (settings.AUTH_USER_MODEL.id)'),
        ),
    ]
