# Generated by Django 4.1.4 on 2024-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='g_type',
            field=models.IntegerField(choices=[(0, 'Excellent'), (1, 'Good'), (2, 'Fair'), (3, 'Weak')], default=0),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'Choice'), (1, 'Coding'), (2, 'Content')], default=0),
        ),
    ]
