# Generated by Django 4.1.4 on 2024-03-18 03:37

import common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_ability_user_info_remove_user_solved_problem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilityhistory',
            name='ability_score',
        ),
        migrations.RemoveField(
            model_name='abilityhistory',
            name='recorded_date',
        ),
        migrations.RemoveField(
            model_name='abilityhistory',
            name='user_ability',
        ),
        migrations.AddField(
            model_name='abilityhistory',
            name='ability',
            field=models.JSONField(default=common.models.get_default_json),
        ),
        migrations.AddField(
            model_name='abilityhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='abilityhistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
