# Generated by Django 4.1.4 on 2024-04-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_usersubmission_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='g_type',
            field=models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Weak', 'Weak')], default='Excellent', max_length=100),
        ),
    ]
