# Generated by Django 4.1.4 on 2023-07-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_ability_id_remove_usersubmission_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='category_id_list',
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.JSONField(default={'data': [1, 2, 3]}, help_text='data: [1, 2, 0]'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='hash_code',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='ability',
            field=models.JSONField(help_text='data: [10, 20, 10]'),
        ),
    ]
