# Generated by Django 4.1.4 on 2023-08-30 05:03

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_task_completeness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='content',
            field=models.JSONField(verbose_name=common.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.JSONField(verbose_name=common.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_id_lists',
            field=models.JSONField(verbose_name=common.models.get_default_json),
        ),
    ]
