# Generated by Django 4.1.4 on 2023-08-30 05:15

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_questionsubmission_content_alter_task_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='content',
            field=models.JSONField(default=common.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.JSONField(default=common.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='task',
            name='question_id_lists',
            field=models.JSONField(default=common.models.get_default_json),
        ),
    ]
