# Generated by Django 4.1.4 on 2023-10-16 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_problemfrequency_remove_questionsubmission_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProblemFrequency',
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submission_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
