# Generated by Django 4.1.4 on 2023-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_delete_problemfrequency_questionsubmission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='qtype',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('computer science', 'Computer Science'), ('system design', 'System Design'), ('behavioral', 'Behavioral')], default='algorithm', max_length=100),
        ),
    ]
