# Generated by Django 4.1.4 on 2023-08-20 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='topic of category', max_length=100)),
                ('group', models.CharField(help_text='group of category', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField(default=1, help_text='bigger means more important')),
                ('diffculty', models.IntegerField(default=1, help_text='diffculty of the category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('diffculty', models.JSONField()),
                ('solution', models.CharField(max_length=4000)),
                ('text_hint', models.JSONField()),
                ('code_hint', models.CharField(max_length=4000)),
                ('resource', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('upvote', models.IntegerField(default=1)),
                ('downvote', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id_list', models.ManyToManyField(to='question.category')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_input', models.JSONField()),
                ('case_output', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coding_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_coding_question', to='question.codingquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id_list', models.ManyToManyField(to='question.category')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_problem', to='question.problem')),
            ],
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='solution_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_question_solution', to='question.solution'),
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('answer_number', models.IntegerField(default=1)),
                ('diffculty', models.JSONField()),
                ('choice', models.JSONField()),
                ('solution', models.CharField(help_text='binary form of the correct answer', max_length=100)),
                ('text_hint', models.JSONField()),
                ('resource', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_question_solution', to='question.solution')),
            ],
        ),
    ]
