# Generated by Django 4.1.4 on 2024-03-18 07:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('step', models.CharField(default='implement', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='algorithm', max_length=100)),
                ('group', models.CharField(default='data_structure', max_length=100)),
                ('name', models.CharField(default='Greedy', max_length=100)),
                ('short_name', models.CharField(default='Grd', max_length=100)),
                ('frequency', models.IntegerField(default=1, help_text='The larger the number, the higher the frequency')),
                ('difficulty', models.IntegerField(default=1, help_text='The larger the number, the higher the difficulty')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField(choices=[(0, 'Choice'), (1, 'Coding'), (2, 'Voice')], default=0)),
                ('step', models.CharField(default='implement', max_length=1000)),
                ('difficulty', models.IntegerField(default=1)),
                ('desc', models.JSONField(default=question.models.get_default_json)),
                ('info', models.JSONField(blank=True, default=question.models.get_default_json)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('tag', models.ManyToManyField(to='question.tag')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.milestone')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'unique_together': {('question', 'milestone')},
            },
        ),
    ]
