# Generated by Django 4.1.4 on 2023-02-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='keypoints',
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='question.category'),
        ),
        migrations.AddField(
            model_name='solution',
            name='keypoints',
            field=models.ManyToManyField(to='question.keypoint'),
        ),
    ]
