# Generated by Django 4.1.4 on 2023-08-27 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='category_id_list',
        ),
        migrations.AddField(
            model_name='solution',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solution_category', to='question.category'),
            preserve_default=False,
        ),
    ]
