# Generated by Django 4.1.4 on 2024-02-27 11:51

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='desc',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='text_hint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='text_hint_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='desc',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='text_hint',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='text_hint_2',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
