# Generated by Django 4.1.4 on 2024-02-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_choicequestion_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='answer_type',
            field=models.IntegerField(choices=[(0, 'Single'), (1, 'Multiple')], default=0),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='type',
            field=models.CharField(default='implement', max_length=1000),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='type',
            field=models.CharField(default='understand', max_length=1000),
        ),
    ]
