# Generated by Django 4.1.4 on 2023-02-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_category_remove_solution_keypoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('OT', 'Others'), ('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('TF', 'True / False')], help_text='type of question', max_length=2),
        ),
    ]
