# Generated by Django 4.1.4 on 2023-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_solution_category_id_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='code_hint',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='resource',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='solution',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='text_hint',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
