# Generated by Django 4.1.4 on 2023-08-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_choicequestion_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='choice',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='diffculty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='resource',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='text_hint',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='diffculty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='resource',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='text_hint',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_input',
            field=models.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_output',
            field=models.JSONField(default='{}'),
        ),
    ]
