# Generated by Django 4.1.4 on 2024-03-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='milestone',
            field=models.ManyToManyField(through='question.QuestionMilestone', to='question.milestone'),
        ),
    ]
