# Generated by Django 4.1.4 on 2024-02-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_choicequestion_answer_type_codingquestion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='question.checklist'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='question.checklist'),
        ),
    ]
