# Generated by Django 4.1.4 on 2023-02-14 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keypoint', to='question.category'),
        ),
    ]
