# Generated by Django 4.1.4 on 2023-02-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_keypoint_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='keypoints',
            new_name='keypoint',
        ),
    ]
