# Generated by Django 4.1.4 on 2024-02-29 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_choicequestion_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='checklist',
        ),
    ]
