# Generated by Django 4.1.4 on 2023-08-27 06:14

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_choicequestion_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestion',
            name='choice',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='resource',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='text_hint',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='resource',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='text_hint',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_input',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='case_output',
            field=models.JSONField(default=question.models.get_default_json),
        ),
    ]
