# Generated by Django 4.1.4 on 2024-04-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_questionmilestone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'Choice'), (1, 'Coding'), (2, 'Interactive')], default=0),
        ),
    ]
