# Generated by Django 4.1.4 on 2024-02-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_checklist_alter_problem_checklist'),
        ('question', '0005_remove_choicequestion_checklist_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checklist',
        ),
    ]
