# Generated by Django 4.1.4 on 2023-02-24 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_rename_keypoints_solution_keypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_category', to='question.category'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_question', to='question.question'),
        ),
    ]
