# Generated by Django 4.1.4 on 2024-04-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_question_q_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.IntegerField(choices=[(0, 'Choice'), (1, 'Coding'), (2, 'Content')], default=0),
        ),
    ]
