# Generated by Django 4.1.4 on 2024-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_delete_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='explain',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
