# Generated by Django 4.1.4 on 2023-09-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_rename_category_id_solution_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='answer',
            field=models.CharField(default=1, help_text='binary form of the correct answer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_question_solution', to='question.solution'),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_question_solution', to='question.solution'),
        ),
    ]
