# Generated by Django 4.1.4 on 2024-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_choicequestion_explain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='checklist',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='milestone',
            field=models.IntegerField(default=1, help_text='binary form of checked milestone'),
        ),
    ]
