# Generated by Django 4.1.4 on 2023-10-16 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_problemfrequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choicequestion',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='solution',
        ),
        migrations.AddField(
            model_name='choicequestion',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solution_problem', to='question.problem'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
