# Generated by Django 4.1.4 on 2024-03-02 08:24

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_usersubmission_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='milestone',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='content',
            field=models.JSONField(default=question.models.get_default_json),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
