# Generated by Django 4.1.4 on 2023-08-09 04:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0009_rename_categoryid_keypoint_category_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="type",
        ),
    ]
