# Generated by Django 4.1.4 on 2024-03-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_remove_usersubmission_milestone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choicequestion',
            old_name='type',
            new_name='stage',
        ),
        migrations.RenameField(
            model_name='codingquestion',
            old_name='type',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='weight',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(default='algorithm', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='frequency',
            field=models.IntegerField(default=1, help_text='The larger the number, the higher the frequency'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='The larger the number, the higher the difficulty'),
        ),
    ]
