# Generated by Django 4.1.4 on 2023-10-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_remove_choicequestion_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicequestion',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choice_question_problem', to='question.problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_question_problem', to='question.problem'),
        ),
    ]
