# Generated by Django 4.1.4 on 2023-07-19 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_remove_keypoint_categoryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='answer',
        ),
        migrations.AddField(
            model_name='solution',
            name='description',
            field=models.JSONField(default='placeholder', help_text='text in the IDE'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.JSONField(help_text='JSON: {array: [1,2,3], target: 10}')),
                ('output', models.JSONField(help_text='JSON: {result: [0,1]}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_question', to='question.question')),
            ],
        ),
    ]
