# Generated by Django 4.1.4 on 2023-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_choicequestion_problem_alter_codingquestion_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemfrequency',
            name='stage',
            field=models.CharField(choices=[('coding', 'Coding'), ('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(default='greedy', help_text='group of category', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='topic',
            field=models.CharField(default='algorithm', help_text='topic of category', max_length=100),
        ),
        migrations.AlterField(
            model_name='problemfrequency',
            name='qtype',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('computer science', 'Computer Science'), ('system design', 'System Design'), ('behavioral', 'Behavioral')], default='algorithm', max_length=100),
        ),
    ]
