# Generated by Django 4.1.4 on 2024-03-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='short_name',
            field=models.CharField(default='Grd', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='Greedy', max_length=100),
        ),
    ]
