# Generated by Django 4.1.4 on 2023-10-23 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_problemfrequency_stage_alter_category_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemfrequency',
            name='qtype',
        ),
        migrations.RemoveField(
            model_name='problemfrequency',
            name='question_id',
        ),
        migrations.AddField(
            model_name='problemfrequency',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='frequency_problem', to='question.problem'),
            preserve_default=False,
        ),
    ]
