# Generated by Django 4.1.4 on 2024-03-16 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_questionfrequency_delete_problemfrequency'),
        ('question', '0012_tag_short_name_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.IntegerField(choices=[(0, 'Choice'), (1, 'Coding'), (2, 'Voice')], default=0)),
                ('step', models.CharField(default='implement', max_length=1000)),
                ('difficulty', models.IntegerField(default=0)),
                ('desc', models.JSONField(default=question.models.get_default_json)),
                ('info', models.JSONField(default=question.models.get_default_json)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
        ),
        migrations.CreateModel(
            name='TagQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.tag')),
            ],
            options={
                'unique_together': {('tag', 'question')},
            },
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='codingquestion',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tagchoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagchoice',
            name='choice_question',
        ),
        migrations.RemoveField(
            model_name='tagchoice',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='tagcoding',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagcoding',
            name='coding_question',
        ),
        migrations.RemoveField(
            model_name='tagcoding',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='coding_question',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChoiceQuestion',
        ),
        migrations.DeleteModel(
            name='CodingQuestion',
        ),
        migrations.DeleteModel(
            name='TagChoice',
        ),
        migrations.DeleteModel(
            name='TagCoding',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.DeleteModel(
            name='UserSubmission',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(through='question.TagQuestion', to='question.tag'),
        ),
    ]
