# Generated by Django 4.1.4 on 2024-03-18 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_question_tagquestion_remove_codingquestion_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('step', models.CharField(default='implement', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='QuestionMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.milestone')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'unique_together': {('question', 'milestone')},
            },
        ),
    ]
