# Generated by Django 4.1.4 on 2023-10-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_codingquestion_begin_codingquestion_during_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='begin',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='description',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='during',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='finish',
            field=models.TextField(max_length=4000),
        ),
    ]
