# Generated by Django 4.1.4 on 2023-10-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_alter_codingquestion_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='code_hint',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
