# Generated by Django 4.1.4 on 2024-03-18 06:14

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_milestone_alter_question_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='info',
            field=models.JSONField(blank=True, default=question.models.get_default_json),
        ),
        migrations.AlterField(
            model_name='tagquestion',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
