# Generated by Django 4.1.4 on 2023-11-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_codingquestion_code_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='begin',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='during',
            field=models.TextField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='finish',
            field=models.TextField(max_length=8000),
        ),
    ]
