# Generated by Django 4.1.4 on 2023-02-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informSet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
