# Generated by Django 4.1.4 on 2024-02-27 03:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('algorithm', 'Algorithm'), ('system design', 'System Design'), ('computer science', 'Computer Science'), ('behavioral', 'Behavioral'), ('resume', 'Resume')], default='algorithm', max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('upvote', models.IntegerField(default=1)),
                ('downvote', models.IntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('coding', 'Coding'), ('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=10)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('origin_link', models.URLField(blank=True, help_text='URL for origin post', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_problem', to='problem.problem')),
            ],
        ),
    ]
