# Generated by Django 4.1.4 on 2024-03-18 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagproblem',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.tag'),
        ),
        migrations.AddField(
            model_name='problemfrequency',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_problem', to='problem.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(through='problem.TagProblem', to='question.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='tagproblem',
            unique_together={('tag', 'problem')},
        ),
    ]
