# Generated by Django 4.1.4 on 2024-02-27 11:51

from django.db import migrations, models
import problem.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='desc',
            field=models.JSONField(default=problem.models.get_default_json),
        ),
    ]
