# Generated by Django 4.1.4 on 2024-02-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_choicequestion_desc_and_more'),
        ('problem', '0002_remove_problem_description_problem_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.tag')),
            ],
            options={
                'unique_together': {('tag', 'problem')},
            },
        ),
    ]
