# Generated by Django 4.1.4 on 2024-03-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('system-design', 'System Design'), ('computer-science', 'Computer Science'), ('behavioral', 'Behavioral'), ('resume', 'Resume')], default='algorithm', max_length=100),
        ),
    ]
