# Generated by Django 4.1.4 on 2024-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_alter_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemfrequency',
            name='stage',
            field=models.CharField(choices=[('oa', 'OA'), ('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=20),
        ),
    ]
