# Generated by Django 4.1.4 on 2024-02-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_remove_choicequestion_checklist_and_more'),
        ('problem', '0003_tagproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='checklist',
            field=models.ManyToManyField(blank=True, to='question.checklist'),
        ),
    ]
