# Generated by Django 4.1.4 on 2024-06-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_problemfrequency_job_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemfrequency',
            name='job_category',
            field=models.CharField(choices=[('swe', 'Software Engineer'), ('mle', 'Machine Learning Engineer'), ('ds', 'Data Scientist')], default='swe', max_length=20),
        ),
    ]
