# Generated by Django 4.1.4 on 2024-03-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_checklist_alter_problem_checklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='Milestone',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='checklist',
            new_name='milestone',
        ),
    ]
