# Generated by Django 4.1.4 on 2024-06-05 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_userinterviewinfo'),
        ('problem', '0006_alter_problemfrequency_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemfrequency',
            name='job_category',
            field=models.CharField(choices=[('swe', 'Software Engineer'), ('fe', 'Frontend Engineer'), ('mle', 'Machine Learning Engineer'), ('ds', 'Data Scientist')], default='swe', max_length=20),
        ),
        migrations.AlterField(
            model_name='problemfrequency',
            name='stage',
            field=models.CharField(choices=[('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=20),
        ),
        migrations.CreateModel(
            name='ProblemCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.company')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
            ],
            options={
                'unique_together': {('problem', 'company')},
            },
        ),
    ]
