# Generated by Django 4.1.4 on 2024-03-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_rename_checklist_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='type',
            field=models.CharField(default='implement', max_length=1000),
        ),
    ]
