# Generated by Django 4.1.4 on 2024-06-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_alter_problemfrequency_job_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemfrequency',
            old_name='job_category',
            new_name='position_type',
        ),
    ]
