# Generated by Django 4.1.4 on 2024-03-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('problem', '0008_milestone_content_type_milestone_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='object_id',
        ),
        migrations.CreateModel(
            name='MilestoneQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.milestone')),
            ],
            options={
                'unique_together': {('milestone', 'content_type', 'object_id')},
            },
        ),
    ]
