# Generated by Django 4.1.4 on 2024-03-16 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_remove_milestone_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('coding', 'Coding'), ('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=10)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('origin_link', models.URLField(blank=True, help_text='URL for origin post', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemFrequency',
        ),
    ]
