# Generated by Django 4.1.4 on 2024-03-16 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0010_questionfrequency_delete_problemfrequency'),
        ('question', '0013_question_tagquestion_remove_codingquestion_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionfrequency',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_question', to='question.question'),
        ),
    ]
