# Generated by Django 4.1.4 on 2024-03-18 03:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0011_questionfrequency_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('coding', 'Coding'), ('phone', 'Phone'), ('onsite', 'Onsite')], default='onsite', max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('origin_link', models.URLField(blank=True, help_text='URL for origin post', max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='milestonequestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='milestonequestion',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='milestonequestion',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='questionfrequency',
            name='question',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='milestone',
        ),
        migrations.DeleteModel(
            name='Milestone',
        ),
        migrations.DeleteModel(
            name='MilestoneQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionFrequency',
        ),
        migrations.AddField(
            model_name='problemfrequency',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequency_problem', to='problem.problem'),
        ),
    ]
