# Generated by Django 4.1.4 on 2024-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0012_problemfrequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagproblem',
            name='difficulty',
            field=models.IntegerField(default=10, help_text='The larger the number, the higher the difficulty'),
        ),
    ]
