# Generated by Django 4.1.4 on 2024-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0013_tagproblem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('system_design', 'System Design'), ('computer_science', 'Computer Science'), ('behavioral', 'Behavioral'), ('resume', 'Resume')], default='algorithm', max_length=100),
        ),
    ]
