# Generated by Django 4.1.4 on 2024-03-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0014_alter_problem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagproblem',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
