name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    # need run on ubuntu-latest and 20.04
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/backend/requirements.txt
    - name: Create ENV file
      run: |
        touch ./src/backend/ENV.py
        echo EMAIL_BACKEND = \'django.core.mail.backends.console.EmailBackend\' >> ./src/backend/ENV.py
        echo ROOT = \'http://127.0.0.1:8000\' >> ./src/backend/ENV.py
    - name: Run Tests
      working-directory: ./src/backend
      run: python manage.py test
