name: Close related issues on merge

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Close related issues
        uses: peter-evans/close-related-issues-action@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
