name: Django CI

on:
  push:
    branches:
  pull_request:
    branches:
    
env:
  ENVIRONMENT: LOCAL
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/backend/requirements.txt

    - name: Run tests
      run: |
        python src/backend/manage.py test src/backend/question
